ALTER TABLE runs ADD COLUMN shield REAL NOT NULL DEFAULT 0;
ALTER TABLE runs ADD COLUMN skr_burned REAL NOT NULL DEFAULT 0;
ALTER TABLE runs ADD COLUMN skr_burn_sig TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS runs_by_burn ON runs (skr_burn_sig);
